/*
 * ClientGUI.java
 *
 * Created on 2008. november 26., 11:55
 */

package shareonclient;

/**
 *
 * @author  Bandita
 */
public class ClientGUI extends javax.swing.JFrame {
    
    ShareOnClient ownerClient;
    
    /** Creates new form ClientGUI */
    public ClientGUI(ShareOnClient ownerClientIn) {
        ownerClient = ownerClientIn;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jHeadPanel = new javax.swing.JPanel();
        jControlPanel = new javax.swing.JPanel();
        jSearchButton = new javax.swing.JButton();
        jLogoutButton = new javax.swing.JButton();
        jSearchField = new javax.swing.JTextField();
        jStatusLabel = new javax.swing.JLabel();
        jResultsPanel = new javax.swing.JPanel();
        jResultsScrollPane = new javax.swing.JScrollPane();
        jResultList = new javax.swing.JList();
        jDownloadButton = new javax.swing.JButton();
        jSharePanel = new javax.swing.JPanel();
        jSharesScrollPane = new javax.swing.JScrollPane();
        jShareList = new javax.swing.JList();
        jShareControlPanel = new javax.swing.JPanel();
        jAddShareButton = new javax.swing.JButton();
        jRemoveShareButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 800, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jHeadPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Controls"));
        jHeadPanel.setLayout(new java.awt.GridBagLayout());

        jControlPanel.setLayout(new java.awt.GridBagLayout());

        jSearchButton.setText("Search!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jControlPanel.add(jSearchButton, gridBagConstraints);

        jLogoutButton.setText("Logout");
        jControlPanel.add(jLogoutButton, new java.awt.GridBagConstraints());

        jSearchField.setText("Type file to search here!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        jControlPanel.add(jSearchField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jHeadPanel.add(jControlPanel, gridBagConstraints);

        jStatusLabel.setText("Status:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jHeadPanel.add(jStatusLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 2.0;
        getContentPane().add(jHeadPanel, gridBagConstraints);

        jResultsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Search results"));
        jResultsPanel.setLayout(new java.awt.GridBagLayout());

        jResultsScrollPane.setViewportView(jResultList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jResultsPanel.add(jResultsScrollPane, gridBagConstraints);

        jDownloadButton.setText("Download");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jResultsPanel.add(jDownloadButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jResultsPanel, gridBagConstraints);

        jSharePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("My shares"));
        jSharePanel.setLayout(new java.awt.GridBagLayout());

        jSharesScrollPane.setViewportView(jShareList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jSharePanel.add(jSharesScrollPane, gridBagConstraints);

        jShareControlPanel.setLayout(new java.awt.GridBagLayout());

        jAddShareButton.setText("Add...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jShareControlPanel.add(jAddShareButton, gridBagConstraints);

        jRemoveShareButton.setText("Remove");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jShareControlPanel.add(jRemoveShareButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jSharePanel.add(jShareControlPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jSharePanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    /* Disabled, because this is not a standalone program, only a GUI.
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGUI().setVisible(true);
            }
        });
    }
    */ 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddShareButton;
    private javax.swing.JPanel jControlPanel;
    private javax.swing.JButton jDownloadButton;
    private javax.swing.JPanel jHeadPanel;
    private javax.swing.JButton jLogoutButton;
    private javax.swing.JButton jRemoveShareButton;
    private javax.swing.JList jResultList;
    private javax.swing.JPanel jResultsPanel;
    private javax.swing.JScrollPane jResultsScrollPane;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JTextField jSearchField;
    private javax.swing.JPanel jShareControlPanel;
    private javax.swing.JList jShareList;
    private javax.swing.JPanel jSharePanel;
    private javax.swing.JScrollPane jSharesScrollPane;
    private javax.swing.JLabel jStatusLabel;
    // End of variables declaration//GEN-END:variables

}
